use std::{collections::HashMap, io::Cursor, str::FromStr};
use rbx_dom_weak::{types::{Attributes, Color3, Ref, Tags, UDim, UDim2, Variant, Vector2, Vector3}, InstanceBuilder, WeakDom};
use serde_json::{json, Value};
use thiserror::Error;
use crate::models::{EncodeRequest, InstanceDoc, PropertyValue};
#[derive(Debug, Error)] pub enum CompatError { #[error("invalid input: {0}")] Input(String), #[error("unsupported property type `{0}`")] UnsupportedType(String), #[error("binary codec error: {0}")] Binary(String) }
fn parse_ref(s:&str)->Result<Ref,CompatError>{Ref::from_str(s).map_err(|_|CompatError::Input(format!("invalid referent `{s}`")))}
fn nums(v:&Value,n:usize)->Result<Vec<f64>,CompatError>{let a=v.as_array().ok_or_else(||CompatError::Input("expected an array".into()))?;if a.len()!=n{return Err(CompatError::Input(format!("expected {n} numbers")))}a.iter().map(|x|x.as_f64().ok_or_else(||CompatError::Input("expected numbers".into()))).collect()}
fn variant(p:&PropertyValue, refs:&HashMap<String,Ref>)->Result<Variant,CompatError>{let k=p.value_type.to_ascii_lowercase();Ok(match k.as_str(){"string"|"content"|"contentid"=>Variant::String(p.value.as_str().ok_or_else(||CompatError::Input("expected string".into()))?.into()),"bool"|"boolean"=>Variant::Bool(p.value.as_bool().ok_or_else(||CompatError::Input("expected bool".into()))?),"int32"|"int"=>Variant::Int32(p.value.as_i64().ok_or_else(||CompatError::Input("expected int".into()))? as i32),"int64"=>Variant::Int64(p.value.as_i64().ok_or_else(||CompatError::Input("expected int64".into()))?),"float32"|"float"=>Variant::Float32(p.value.as_f64().ok_or_else(||CompatError::Input("expected float".into()))? as f32),"float64"|"double"=>Variant::Float64(p.value.as_f64().ok_or_else(||CompatError::Input("expected float".into()))?),"vector2"=>{let v=nums(&p.value,2)?;Variant::Vector2(Vector2::new(v[0] as f32,v[1] as f32))},"vector3"=>{let v=nums(&p.value,3)?;Variant::Vector3(Vector3::new(v[0] as f32,v[1] as f32,v[2] as f32))},"color3"=>{let v=nums(&p.value,3)?;Variant::Color3(Color3::new(v[0] as f32,v[1] as f32,v[2] as f32))},"udim"=>{let v=nums(&p.value,2)?;Variant::UDim(UDim::new(v[0] as f32,v[1] as i32))},"udim2"=>{let v=nums(&p.value,4)?;Variant::UDim2(UDim2::new(v[0] as f32,v[1] as i32,v[2] as f32,v[3] as i32))},"ref"|"instance"|"instanceref"=>Variant::Ref(*refs.get(p.value.as_str().ok_or_else(||CompatError::Input("expected ref".into()))?).ok_or_else(||CompatError::Input("unknown ref".into()))?),"attributes"=>{let mut a=Attributes::new();for (n,v) in p.value.as_object().ok_or_else(||CompatError::Input("attributes must be an object".into()))?{a.insert(n.clone(),variant(v,refs)?);}Variant::Attributes(a)},"tags"=>Variant::Tags(Tags::from(p.value.as_array().ok_or_else(||CompatError::Input("tags must be an array".into()))?.iter().map(|v|v.as_str().map(String::from).ok_or_else(||CompatError::Input("tags must be strings".into()))).collect::<Result<Vec<_>,_>>()?)),x=>return Err(CompatError::UnsupportedType(x.into()))})}
fn check(r:&EncodeRequest)->Result<(),CompatError>{if r.instances.is_empty(){return Err(CompatError::Input("instances cannot be empty".into()))}let mut s=HashMap::new();for i in &r.instances{if i.referent.is_empty()||i.class_name.is_empty(){return Err(CompatError::Input("referent and class_name are required".into()))}if s.insert(&i.referent,()).is_some(){return Err(CompatError::Input("duplicate referent".into()))}}for i in &r.instances{if let Some(p)=&i.parent{if !s.contains_key(p){return Err(CompatError::Input("missing parent".into()))}}}Ok(())}
pub fn encode(r:&EncodeRequest)->Result<Vec<u8>,CompatError>{check(r)?;let refs=r.instances.iter().map(|i|Ok((i.referent.clone(),parse_ref(&i.referent)?))).collect::<Result<HashMap<_,_>,CompatError>>()?;let mut d=WeakDom::new(InstanceBuilder::new("DataModel"));let root=d.root_ref();let mut inserted=HashMap::new();let mut left=r.instances.iter().collect::<Vec<_>>();while !left.is_empty(){let before=left.len();let mut next=Vec::new();for i in left{let parent=match &i.parent{None=>root,Some(p)=>match inserted.get(p){Some(x)=>*x,None=>{next.push(i);continue}}};let mut b=InstanceBuilder::new(i.class_name.clone()).with_name(i.name.clone()).with_referent(*refs.get(&i.referent).unwrap());for(n,p)in&i.properties{b=b.with_property(n.clone(),variant(p,&refs)?)}if !i.attributes.is_empty(){let p=PropertyValue{value_type:"Attributes".into(),value:serde_json::to_value(&i.attributes).map_err(|e|CompatError::Input(e.to_string()))?};b=b.with_property("Attributes",variant(&p,&refs)?)}if !i.tags.is_empty(){b=b.with_property("Tags",Variant::Tags(Tags::from(i.tags.clone())))}inserted.insert(i.referent.clone(),d.insert(parent,b));}if next.len()==before{return Err(CompatError::Input("parent graph contains a cycle".into()))}left=next}let mut out=Vec::new();rbx_binary::to_writer(&mut out,&d,&[root]).map_err(|e|CompatError::Binary(e.to_string()))?;Ok(out)}
fn json_variant(v:&Variant)->(String,Value){match v{Variant::String(x)=>("String".into(),json!(x)),Variant::Bool(x)=>("Bool".into(),json!(x)),Variant::Int32(x)=>("Int32".into(),json!(x)),Variant::Int64(x)=>("Int64".into(),json!(x)),Variant::Float32(x)=>("Float32".into(),json!(x)),Variant::Float64(x)=>("Float64".into(),json!(x)),Variant::Vector2(x)=>("Vector2".into(),json!([x.x,x.y])),Variant::Vector3(x)=>("Vector3".into(),json!([x.x,x.y,x.z])),Variant::Color3(x)=>("Color3".into(),json!([x.r,x.g,x.b])),Variant::Ref(x)=>("Ref".into(),json!(x.to_string())),Variant::Attributes(x)=>("Attributes".into(),json!(x.iter().map(|(n,v)|(n,json_variant(v))).collect::<std::collections::BTreeMap<_,_>>())),Variant::Tags(x)=>("Tags".into(),json!(x.iter().collect::<Vec<_>>())),x=>(format!("{:?}",x.ty()),Value::Null)}}
pub fn decode(bytes:&[u8])->Result<Value,CompatError>{let d=rbx_binary::from_reader(Cursor::new(bytes)).map_err(|e|CompatError::Binary(e.to_string()))?;let root=d.root_ref();let mut out=Vec::new();for i in d.descendants_of(root).skip(1){let mut props=serde_json::Map::new();let mut attrs=serde_json::Map::new();let mut tags=Vec::new();for(n,v)in&i.properties{match v{Variant::Attributes(a)=>for(an,av)in a.iter(){let(k,x)=json_variant(av);attrs.insert(an.clone(),json!({"value_type":k,"value":x}));},Variant::Tags(t)=>tags.extend(t.iter().map(String::from)),_=>{let(k,x)=json_variant(v);props.insert(n.to_string(),json!({"value_type":k,"value":x}));}}}let parent=if i.parent()==root{None}else{d.get_by_ref(i.parent()).map(|p|p.referent().to_string())};out.push(json!({"referent":i.referent().to_string(),"class_name":i.class.to_string(),"name":i.name,"parent":parent,"properties":props,"attributes":attrs,"tags":tags}));}Ok(json!({"instances":out}))}
pub fn validate(bytes:&[u8])->Result<(),CompatError>{rbx_binary::from_reader(Cursor::new(bytes)).map(|_|()).map_err(|e|CompatError::Binary(e.to_string()))}
