name: Run Dockerfile

on:
  push:
    branches: [ "main" ]

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t my-local-image:latest .
      - name: Run Docker Container
        run: docker run --rm my-local-image:latest
